server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT

      routes:
        - id: discovery-server
          uri: lb://discovery-server
          predicates:
            - Path=/eureka/**

        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/orders/**

        - id: client-service
          uri: lb://clients-service
          predicates:
            - Path=/api/clients/**


