server:
  port: 8081

spring:
  application:
    name: clients-service

  jpa:
    jpa:
      show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/simu_user_service
    username: root
    password:


eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
