server:
  port: 8082

spring:
  application:
    name: products-service

  data:
     mongodb:
        uri: mongodb://localhost:27017/simu_product_service
        database: simu_product_service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
